version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "37017:27017"
    volumes:
      - '/Users/allenkao/.mount/mongodb:/data/db'
    restart: on-failure

  redis:
    image: redis
    container_name: redis
    ports:
      - "36379:6379"
    restart: on-failure

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: template7
    ports:
      - "33306:3306"
    restart: on-failure
