log:
  level: DEBUG

gin:
  listenPort: 8080
  mode: debug
  shutdownTimeout: 10


facebook:
  appId: ""
  secret: ""
  callback: "http://localhost:8080/api/v1/sign-in/facebook/callback"

mongo:
  db: template7
  host: 10.0.0.10
  port: 27017
  username:
  password:

redis:
  host: "10.0.0.10:6379"
  password: