env: dev

logger:
  level: debug

service:
  port: 8080

db:
  sql:
    db: template7
    host: host.docker.internal
    port: 33306
    username: admin
    password: password
    connection:
      min: 4
      max: 8
  nosql:
    db: template7
    host: host.docker.internal
    port: 37017
    username: admin
    password: password

cache:
  host: "host.docker.internal:36379"
  password:

auth:
  rbacModelPath: "./config/rbac_model.conf"