apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    run: backend
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: backend-port
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /backend/config
      volumes:
        - name: config-volume
          configMap:
            name: backend-conf
      