apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    run: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: backend-port
      protocol: TCP
      name: backend
      nodePort: {{ .Values.service.externalPort }}
  selector:
    run: backend
